export { contrastRatio, hexToRgb, rgbToHex, parseRgb, blendRgbaOverRgb, scoreLabel } from './contrast.js'
export { collectElements } from './dom-analyzer.js'
export { analyzeElements } from './analyzer.js'
export { analyzeDesign } from './design-analyzer.js'
export type { ElementDatum, Failure, WcagResult } from './dom-analyzer.js'
export type { DesignFailure } from './rules/font-size.js'
export type { DesignResult } from './design-analyzer.js'
