export { contrastRatio, hexToRgb, rgbToHex, parseRgb, blendRgbaOverRgb, scoreLabel } from './contrast'
export { collectElements } from './dom-analyzer'
export { analyzeElements } from './analyzer'
export { analyzeDesign } from './design-analyzer'
export type { ElementDatum, Failure, WcagResult } from './dom-analyzer'
export type { DesignFailure } from './rules/font-size'
export type { DesignResult } from './design-analyzer'
