function detectAiContent(text, html, querySelector, querySelectorAll) {
  var results = [];
  var signals = [];
  var confidence = 0;
  var lowText = text.toLowerCase();
  var textLen = text.length;

  // 1. AI disclosure signals
  var disclosurePatterns = [
    'generated by ai', 'generated by artificial intelligence',
    'written by ai', 'created by ai', 'produced by ai',
    'ai-generated content', 'ai-generated article',
    'automatically generated', 'ai assistant',
    'powered by ai', 'curated by ai',
    'this content was ai', 'ai written',
    'content generated using ai',
    'machine generated', 'automatically written',
    'ai-authored', 'ai author',
    'disclaimer: ai', 'ai disclosure',
    'this response was generated', 'this article was generated',
    'synthesized by ai', 'ai synthesis',
    'generated using artificial intelligence',
    'written with the assistance of ai',
    'ai was used in the creation',
    'partially generated using',
    'includes ai-generated',
    'created with ai tools',
    'ai-assisted writing', 'ai assisted',
    'produced with the help of ai',
    'contains ai-generated',
    'sections of this article were generated',
    'incorporates ai output',
    'ai-generated text', 'ai generated'
  ];

  for (var di = 0; di < disclosurePatterns.length; di++) {
    if (lowText.indexOf(disclosurePatterns[di]) !== -1) {
      signals.push({ type: 'ai-disclosure', detail: 'Contains AI disclosure: "' + disclosurePatterns[di] + '"', weight: 0.3 });
      confidence += 30;
      break;
    }
  }

  // 2. Generic AI phrasing patterns
  var aiPhrases = [
    'as an ai', 'as a large language model', 'as an ai language model',
    'i cannot provide', 'i cannot confirm', 'i cannot access',
    'i do not have access', 'i don\'t have access',
    'i am an ai', 'i am a language model',
    'i am not able to browse', 'i cannot browse',
    'my knowledge cutoff', 'knowledge cutoff',
    'i don\'t have personal', 'i don\'t have feelings',
    'as an llm', 'as a language model',
    'i apologize, but i cannot', 'sorry, but i cannot',
    'i don\'t have the ability', 'i do not have the ability',
    'i cannot guarantee', 'please note that i',
    'is beyond my scope', 'is outside my scope',
    'i don\'t have real-time',
    'based on my training data', 'based on my training',
    'as of my last update', 'as of my last knowledge update',
    'i\'m an ai assistant', 'i am an ai assistant',
    'i was trained on', 'my training data includes',
    'i cannot process real-time',
    'i don\'t have access to real-time',
    'i\'d be happy to help you with',
    'let me know if you have any questions',
    'is there anything else i can help',
    'i can provide an overview',
    'here is a summary of',
    'as an ai model',
    'as an ai system',
    'i\'m here to help',
    'i\'m designed to'
  ];

  for (var pi = 0; pi < aiPhrases.length; pi++) {
    if (lowText.indexOf(aiPhrases[pi]) !== -1) {
      signals.push({ type: 'ai-phrasing', detail: 'AI phrasing pattern: "' + aiPhrases[pi] + '"', weight: 0.25 });
      confidence += 25;
    }
  }

  // 3. HTML generator meta tag
  var generatorMeta = querySelector('meta[name="generator"]');
  if (generatorMeta) {
    var genContent = (generatorMeta.content || '').toLowerCase();
    var aiGenerators = ['chatgpt', 'gpt-', 'openai', 'claude', 'anthropic', 'ai', 'bard', 'gemini',
      'copilot', 'perplexity', 'mistral', 'llama', 'deepseek',
      'midjourney', 'dall-e', 'dalle', 'stable diffusion',
      'writesonic', 'jasper', 'copy.ai', 'wordtune',
      'grammarly', 'rytr', 'you.com', 'character.ai'
    ];
    for (var gi = 0; gi < aiGenerators.length; gi++) {
      if (genContent.indexOf(aiGenerators[gi]) !== -1) {
        signals.push({ type: 'ai-generator-tag', detail: 'HTML meta generator: "' + genContent + '"', weight: 0.15 });
        confidence += 15;
        break;
      }
    }
  }

  // 4. Missing author attribution
  var authorMeta = querySelector('meta[name="author"]');
  var bylineEls = querySelectorAll('[class*="author"], [class*="byline"], [id*="author"], [id*="byline"]');
  var hasAuthor = authorMeta && (authorMeta.content || '').trim().length > 0;
  var hasByline = false;
  for (var bli = 0; bli < bylineEls.length; bli++) {
    if ((bylineEls[bli].textContent || '').trim().length > 0 &&
        bylineEls[bli].offsetHeight > 0) {
      hasByline = true; break;
    }
  }
  if (!hasAuthor && !hasByline && textLen > 200) {
    signals.push({ type: 'missing-author', detail: 'No author attribution or byline found', weight: 0.1 });
    confidence += 10;
  }

  // 5. Content repetition
  var sentences = [];
  if (textLen > 500) {
    sentences = text.match(/[^.!?]+[.!?]+/g) || [];
    if (sentences.length >= 5) {
      var uniqueSentences = new Set(sentences.map(function(s) { return s.trim().toLowerCase(); }));
      var ratio = uniqueSentences.size / sentences.length;
      if (ratio < 0.7) {
        signals.push({ type: 'high-repetition', detail: 'Unusual sentence repetition ratio: ' + ratio.toFixed(2), weight: 0.15 });
        confidence += 15;
      }
    }
  }

  // 6. Uniform sentence length
  if (textLen > 500 && sentences.length >= 10) {
    var lengths = sentences.map(function(s) { return s.trim().split(/\s+/).length; });
    var sum = 0;
    for (var li = 0; li < lengths.length; li++) { sum += lengths[li]; }
    var mean = sum / lengths.length;
    var variance = 0;
    for (var vi = 0; vi < lengths.length; vi++) { variance += Math.pow(lengths[vi] - mean, 2); }
    variance /= lengths.length;
    var stdDev = Math.sqrt(variance);
    if (stdDev < 2.5 && mean > 8 && mean < 25) {
      signals.push({ type: 'uniform-sentence-length', detail: 'Unusually uniform sentence length (std dev: ' + stdDev.toFixed(1) + ')', weight: 0.1 });
      confidence += 10;
    }
  }

  // 7. Generic structure absences
  if (textLen > 200) {
    var hadElements = false;
    if (querySelector('article')) hadElements = true;
    if (querySelector('time')) hadElements = true;
    if (!querySelector('h1, h2, h3') && !hadElements) {
      if (textLen > 500) {
        signals.push({ type: 'missing-structure', detail: 'Significant text without headings or article structure', weight: 0.05 });
        confidence += 5;
      }
    }
  }

  if (confidence > 100) confidence = 100;

  signals.sort(function(a, b) { return b.weight - a.weight; });

  var level = 'unlikely';
  if (confidence >= 60) {
    level = 'likely';
    results.push({
      ruleId: 'ai-generated-content',
      ruleName: 'Content may be AI-generated',
      category: 'ai',
      selector: 'body',
      description: 'AI detection confidence: ' + confidence + '%. Signals: ' + signals.length,
      severity: confidence >= 80 ? 'medium' : 'info',
      value: confidence + '% confidence',
      expected: 'human-authored content expected (no AI signals)'
    });
  } else if (confidence >= 30) {
    level = 'possible';
    results.push({
      ruleId: 'ai-generated-content',
      ruleName: 'Content may be AI-generated',
      category: 'ai',
      selector: 'body',
      description: 'AI detection confidence: ' + confidence + '%. Weak signals detected.',
      severity: 'info',
      value: confidence + '% confidence',
      expected: 'human-authored content expected (no AI signals)'
    });
  }

  return {
    failures: results,
    confidence: confidence,
    level: level,
    signals: signals,
    totalChecks: 1
  };
}

async function runAiDetectionChecks(page) {
  var fnStr = detectAiContent.toString();
  return page.evaluate(function(fnStr) {
    var detectFn = new Function('return ' + fnStr)();
    var text = document.body ? document.body.innerText || '' : '';
    var html = document.documentElement ? document.documentElement.innerHTML || '' : '';
    return detectFn(text, html,
      function(s) { return document.querySelector(s); },
      function(s) { return document.querySelectorAll(s); }
    );
  }, fnStr);
}

module.exports = { runAiDetectionChecks, detectAiContent };
