import { describe, it, expect } from 'vitest'

const { detectAiContent } = require('./ai-detect.js')

function qs(els) {
  return function(sel) {
    var result = null
    for (var i = 0; i < els.length; i++) {
      if (els[i].matches && els[i].matches(sel)) {
        result = els[i]
        break
      }
    }
    return result
  }
}

function qsa(els) {
  return function(sel) {
    var matches = []
    for (var i = 0; i < els.length; i++) {
      if (els[i].matches && els[i].matches(sel)) {
        matches.push(els[i])
      }
    }
    return matches
  }
}

function el(tag, attrs, children) {
  var content = ''
  var attributes = {}
  var offsetHeight = 0
  if (attrs) {
    if (attrs.content !== undefined) content = attrs.content
    if (attrs.offsetHeight !== undefined) offsetHeight = attrs.offsetHeight
    attributes = attrs
  }
  var textContent = children || ''
  return {
    tagName: tag.toUpperCase(),
    getAttribute: function(name) { return attributes[name] !== undefined ? String(attributes[name]) : null },
    matches: function(sel) {
      if (sel === tag) return true
      if (sel.indexOf('[') !== -1) {
        var match = sel.match(/\[([\w-]+)(\*)?=(?:"([^"]*)"|'([^']*)')?\]/)
        if (match) {
          var attrName = match[1]
          var isSubstring = match[2] === '*'
          var attrVal = match[3] || match[4] || ''
          var val = attributes[attrName]
          if (val === undefined) { val = attributes[attrName.replace('*', '')] }
          if (val === undefined) return false
          if (isSubstring) return String(val).indexOf(attrVal) !== -1
          return String(val) === attrVal
        }
        var presenceMatch = sel.match(/\[([\w-]+)\]/)
        if (presenceMatch) {
          return attributes[presenceMatch[1]] !== undefined
        }
      }
      if (sel.indexOf('.') !== -1) {
        var cls = sel.split('.')[1]
        var attrs = attributes.class || ''
        return attrs.split(' ').indexOf(cls) !== -1
      }
      return false
    },
    content: content,
    textContent: textContent,
    offsetHeight: offsetHeight
  }
}

describe('detectAiContent', () => {
  it('detects AI disclosure patterns', () => {
    var result = detectAiContent(
      'This content was generated by AI. It provides an overview.',
      '<html></html>',
      qs([]),
      qsa([])
    )
    expect(result.confidence).toBeGreaterThanOrEqual(30)
    expect(result.level).toBe('possible')
    expect(result.signals).toHaveLength(1)
    expect(result.signals[0].type).toBe('ai-disclosure')
    expect(result.failures).toHaveLength(1)
  })

  it('detects AI phrasing patterns', () => {
    var result = detectAiContent(
      'As an AI language model, I can tell you that my knowledge cutoff means I cannot provide current info.',
      '<html></html>',
      qs([]),
      qsa([])
    )
    expect(result.confidence).toBeGreaterThanOrEqual(50)
    expect(result.level).toBe('likely')
    expect(result.signals.length).toBeGreaterThanOrEqual(2)
  })

  it('detects AI generator meta tag', () => {
    var metaEl = el('meta', { name: 'generator', content: 'ChatGPT' })
    var result = detectAiContent(
      'Some generic body text here for the page content.',
      '<html><head><meta name="generator" content="ChatGPT"></head></html>',
      qs([metaEl]),
      qsa([metaEl])
    )
    expect(result.confidence).toBeGreaterThanOrEqual(15)
    expect(result.signals).toHaveLength(1)
    expect(result.signals[0].type).toBe('ai-generator-tag')
  })

  it('signals missing author on long content', () => {
    var text = Array(10).join('Valid paragraph text that is long enough to trigger the author check. ')
    var result = detectAiContent(text, '<html></html>', qs([]), qsa([]))
    expect(result.confidence).toBeGreaterThanOrEqual(10)
    var hasMissingAuthor = result.signals.some(function(s) { return s.type === 'missing-author' })
    expect(hasMissingAuthor).toBe(true)
  })

  it('does not signal missing author when author meta is present', () => {
    var metaEl = el('meta', { name: 'author', content: 'Jane Smith' })
    var text = Array(10).join('Some long text that would normally trigger the author check. ')
    var result = detectAiContent(text, '<html></html>', qs([metaEl]), qsa([metaEl]))
    var hasMissingAuthor = result.signals.some(function(s) { return s.type === 'missing-author' })
    expect(hasMissingAuthor).toBe(false)
  })

  it('does not signal missing author when byline is present', () => {
    var bylineEl = el('div', { class: 'author', offsetHeight: 20 }, 'By John Doe')
    var text = Array(10).join('Some long text that would normally trigger the author check. ')
    var result = detectAiContent(text, '<html></html>', qs([]), qsa([bylineEl]))
    var hasMissingAuthor = result.signals.some(function(s) { return s.type === 'missing-author' })
    expect(hasMissingAuthor).toBe(false)
  })

  it('detects content repetition', () => {
    var text = Array(11).join('This is a sentence that gets repeated over and over again. ')
    var result = detectAiContent(text, '<html></html>', qs([]), qsa([]))
    expect(result.confidence).toBeGreaterThanOrEqual(15)
    var hasRepetition = result.signals.some(function(s) { return s.type === 'high-repetition' })
    expect(hasRepetition).toBe(true)
  })

  it('detects uniform sentence length', () => {
    var sentences = []
    for (var i = 0; i < 12; i++) {
      sentences.push('This is a sentence with exactly fourteen words in it overall.')
    }
    var result = detectAiContent(sentences.join(' '), '<html></html>', qs([]), qsa([]))
    expect(result.confidence).toBeGreaterThanOrEqual(10)
    var hasUniform = result.signals.some(function(s) { return s.type === 'uniform-sentence-length' })
    expect(hasUniform).toBe(true)
  })

  it('signals missing structure for long content without headings', () => {
    var text = Array(30).join('Long paragraph text without any heading structure at all. ')
    var result = detectAiContent(text, '<html></html>', qs([]), qsa([]))
    var hasMissingStruct = result.signals.some(function(s) { return s.type === 'missing-structure' })
    expect(hasMissingStruct).toBe(true)
  })

  it('does not signal missing structure when article tag present', () => {
    var articleEl = el('article')
    var text = Array(30).join('Long paragraph text without any heading structure but inside article. ')
    var result = detectAiContent(text, '<html></html>', qs([articleEl]), qsa([articleEl]))
    var hasMissingStruct = result.signals.some(function(s) { return s.type === 'missing-structure' })
    expect(hasMissingStruct).toBe(false)
  })

  it('returns 0 confidence for clean human-authored content', () => {
    var metaEl = el('meta', { name: 'author', content: 'Jane Smith' })
    var text = 'I went to Japan last spring and it was amazing. The cherry blossoms were in full bloom when I arrived in Kyoto. I spent three days exploring temples and wandering through narrow streets. On the fourth day, I took a bullet train to Tokyo. The contrast between Kyoto and Tokyo was striking. I visited Shibuya Crossing and ate fresh sushi at Tsukiji Market.'
    var result = detectAiContent(text, '<html></html>', qs([metaEl]), qsa([metaEl]))
    expect(result.confidence).toBe(0)
    expect(result.level).toBe('unlikely')
    expect(result.failures).toHaveLength(0)
  })

  it('sorts signals by weight descending', () => {
    var text = 'This content was generated by AI. As an AI language model, my knowledge cutoff means I cannot provide current information.'
    var metaEl = el('meta', { name: 'generator', content: 'ChatGPT' })
    var result = detectAiContent(text, '<html></html>', qs([metaEl]), qsa([metaEl]))
    for (var i = 0; i < result.signals.length - 1; i++) {
      expect(result.signals[i].weight).toBeGreaterThanOrEqual(result.signals[i + 1].weight)
    }
  })

  it('caps confidence at 100', () => {
    var text = Array(5).join('This content was generated by AI. As an AI language model, I cannot provide real-time data. My knowledge cutoff prevents me from accessing current information. I do not have the ability to verify facts independently. ')
    var metaEl = el('meta', { name: 'generator', content: 'ChatGPT' })
    var result = detectAiContent(text, '<html></html>', qs([metaEl]), qsa([metaEl]))
    expect(result.confidence).toBeLessThanOrEqual(100)
  })

  it('handles empty text gracefully', () => {
    var result = detectAiContent('', '<html></html>', qs([]), qsa([]))
    expect(result.confidence).toBe(0)
    expect(result.level).toBe('unlikely')
    expect(result.failures).toHaveLength(0)
    expect(result.signals).toHaveLength(0)
  })

  it('reports likely level at high confidence', () => {
    var result = detectAiContent(
      'This content was generated by AI. As an AI language model, I cannot provide real-time information. My knowledge cutoff prevents me from accessing current data. I do not have the ability to verify facts.',
      '<html></html>',
      qs([]),
      qsa([])
    )
    if (result.confidence >= 60) {
      expect(result.level).toBe('likely')
      expect(result.failures).toHaveLength(1)
    }
  })

  it('reports medium severity at very high confidence', () => {
    var text = 'This content was generated by AI. As an AI language model, my knowledge cutoff means I cannot provide current information. I cannot access real-time data or browse the internet. I do not have the ability to verify facts independently. This response was generated based on my training data.'
    var metaEl = el('meta', { name: 'generator', content: 'ChatGPT' })
    var result = detectAiContent(text, '<html></html>', qs([metaEl]), qsa([metaEl]))
    if (result.confidence >= 80) {
      expect(result.failures[0].severity).toBe('medium')
    }
  })
})
