const fs = require('fs');

function recommend(auditPath, extractPath) {
  const audit = JSON.parse(fs.readFileSync(auditPath, 'utf-8'));
  const extract = extractPath
    ? JSON.parse(fs.readFileSync(extractPath, 'utf-8'))
    : null;

  const groups = [];

  if (!audit.wcag || !audit.wcag.failures) {
    return { error: 'No WCAG data found in audit file. Run with --wcag flag.' };
  }

  for (const f of audit.wcag.failures) {
    groups.push({
      severity: f.contrastRatio < 3 ? 'high' : 'medium',
      type: 'contrast',
      selector: f.selector,
      text: f.text.slice(0, 60),
      foreground: f.foreground,
      background: f.background,
      ratio: f.contrastRatio,
      required: f.required,
      recommendation:
        f.contrastRatio < f.required
          ? `Increase contrast on "${f.selector}" from ${f.foreground} (ratio ${f.contrastRatio}:1, needs ≥ ${f.required}:1). Darken foreground or lighten background.`
          : ''
    });
  }

  if (extract && extract.styles && extract.styles.colors) {
    function hexToRgb(hex) {
      const m = hex.match(/^#?([a-f0-9]{2})([a-f0-9]{2})([a-f0-9]{2})$/i);
      if (!m) return hex;
      return `rgb(${parseInt(m[1], 16)}, ${parseInt(m[2], 16)}, ${parseInt(m[3], 16)})`;
    }

    const colorFreq = extract.styles.colors;
    const failingColors = {};
    for (const f of audit.wcag.failures) {
      const key = hexToRgb(f.foreground);
      const match = colorFreq[key];
      if (match) {
        failingColors[key] = { count: (failingColors[key]?.count || 0) + 1, totalUsage: match.count };
      }
    }

    for (const [color, info] of Object.entries(failingColors)) {
      if (info.totalUsage >= 10) {
        groups.push({
          severity: 'high',
          type: 'token',
          color,
          failures: info.count,
          totalUsage: info.totalUsage,
          exampleSelectors: colorFreq[color]?.selectors?.slice(0, 3) || [],
          recommendation:
            `Design token ${color} fails WCAG on ${info.count} element(s) and is used ${info.totalUsage} times across the site. ` +
            `Consider updating this token (e.g., darken for better contrast).`
        });
      }
    }
  }

  groups.sort((a, b) => {
    const sev = { high: 0, medium: 1, low: 2 };
    return (sev[a.severity] ?? 2) - (sev[b.severity] ?? 2);
  });

  return {
    url: audit.url,
    timestamp: audit.timestamp,
    summary: {
      totalFailures: audit.wcag.failCount,
      score: audit.wcag.score,
      tokenIssues: groups.filter(g => g.type === 'token').length
    },
    recommendations: groups,
    markdown: renderMarkdown(audit, groups)
  };
}

function renderMarkdown(audit, groups) {
  const lines = [];
  lines.push('# Liveviewer Recommendation Report');
  lines.push('');
  lines.push(`**URL:** ${audit.url}`);
  lines.push(`**WCAG Score:** ${audit.wcag.score}% (${audit.wcag.passCount}/${audit.wcag.totalElements} pass)`);
  lines.push('');

  const high = groups.filter(g => g.severity === 'high');
  const medium = groups.filter(g => g.severity === 'medium');

  if (high.length > 0) {
    lines.push('## 🔴 High Severity');
    for (const r of high) {
      if (r.type === 'token') {
        lines.push(`- **Token:** \`${r.color}\` — ${r.recommendation}`);
      } else {
        lines.push(`- \`${r.selector}\`: ${r.recommendation}`);
      }
    }
    lines.push('');
  }

  if (medium.length > 0) {
    lines.push('## 🟡 Medium Severity');
    for (const r of medium) {
      lines.push(`- \`${r.selector}\`: ${r.recommendation}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push(`_Generated by Liveviewer recommend at ${new Date().toISOString()}_`);
  return lines.join('\n');
}

module.exports = { recommend };
